DEFINE sql:select-option "order" 
PREFIX brso: <http://purl.jp/bio/10/brso/>
PREFIX sio: <http://semanticscience.org/resource/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX bmpo: <http://purl.bioontology.org/ontology/BMPO/>

SELECT DISTINCT
    ?Resource
    ?id
    (group_concat(distinct ?phenotype;separator = ", ") AS ?phenotype)
    (group_concat(distinct ?journal ;separator = ",") AS ?journal)
    (group_concat(distinct ?origin;separator = ", ") AS ?origin_all)
FROM <{{graph}}>
WHERE {
    {
        ?Resource a brso:BiologicalResource ;
            dcterms:identifier ?id ;
            bmpo:stage_egg ?StageEgg .
        ?StageEgg a brso:BiologicalResourceEgg .
        
        OPTIONAL {?Resource dcterms:isReferencedBy ?journal .}
        OPTIONAL {?Resource brso:derived_from ?origin .}
        OPTIONAL {
            ?StageEgg sio:SIO_001279 _:b1 .
            _:b1 a sio:SIO_010056 ;
                rdfs:label ?phenotype .
            filter(LANG(?phenotype) = '')
        }
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dcterms:identifier ?id ;
            bmpo:stage_larva ?StageLarva .
        ?StageLarva a brso:BiologicalResourceLarva .

        OPTIONAL {?Resource dcterms:isReferencedBy ?journal .}
        OPTIONAL {?Resource brso:derived_from ?origin .}
        OPTIONAL {
            ?StageLarva sio:SIO_001279 _:b2 .
            _:b2 a sio:SIO_010056 ;
                rdfs:label ?phenotype .
            filter(LANG(?phenotype) = '')
        }
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dcterms:identifier ?id ;
            bmpo:stage_pupa ?StagePupa .
        ?StagePupa a brso:BiologicalResourcePupa .

        OPTIONAL {?Resource dcterms:isReferencedBy ?journal .}
        OPTIONAL {?Resource brso:derived_from ?origin .}  
        OPTIONAL {
            ?StagePupa sio:SIO_001279 _:b3 .
            _:b3 a sio:SIO_010056 ;
                rdfs:label ?phenotype .
            filter(LANG(?phenotype) = '')
        }
    } UNION {
        ?Resource a brso:BiologicalResource ;
            dcterms:identifier ?id ;
            bmpo:stage_adult ?StageAdult .
        ?StageAdult a brso:BiologicalResourceAdult .

        OPTIONAL {?Resource dcterms:isReferencedBy ?journal .}
        OPTIONAL {?Resource brso:derived_from ?origin .}  
        OPTIONAL {
            ?StageAdult sio:SIO_001279 _:b4 .
            _:b4 a sio:SIO_010056 ;
                rdfs:label ?phenotype .
            filter(LANG(?phenotype) = '')
        }
    }
}
ORDER BY ?id
